# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\econ_ui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_econ_ui(object):
    def setupUi(self, econ_ui):
        econ_ui.setObjectName("econ_ui")
        econ_ui.resize(714, 498)
        self.gridLayout = QtWidgets.QGridLayout(econ_ui)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(econ_ui)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.input_box = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.input_box.sizePolicy().hasHeightForWidth())
        self.input_box.setSizePolicy(sizePolicy)
        self.input_box.setObjectName("input_box")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.input_box)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.find_combo = QtWidgets.QComboBox(self.input_box)
        self.find_combo.setObjectName("find_combo")
        self.find_combo.addItem("")
        self.find_combo.addItem("")
        self.find_combo.addItem("")
        self.find_combo.addItem("")
        self.find_combo.addItem("")
        self.gridLayout_3.addWidget(self.find_combo, 0, 1, 1, 1)
        self.find_label = QtWidgets.QLabel(self.input_box)
        self.find_label.setObjectName("find_label")
        self.gridLayout_3.addWidget(self.find_label, 0, 0, 1, 1)
        self.period_label = QtWidgets.QLabel(self.input_box)
        self.period_label.setObjectName("period_label")
        self.gridLayout_3.addWidget(self.period_label, 3, 0, 1, 1)
        self.know_combo = QtWidgets.QComboBox(self.input_box)
        self.know_combo.setObjectName("know_combo")
        self.know_combo.addItem("")
        self.know_combo.addItem("")
        self.know_combo.addItem("")
        self.know_combo.addItem("")
        self.gridLayout_3.addWidget(self.know_combo, 1, 1, 1, 1)
        self.period_info = QtWidgets.QLabel(self.input_box)
        self.period_info.setObjectName("period_info")
        self.gridLayout_3.addWidget(self.period_info, 3, 2, 1, 1)
        self.period_edit = QtWidgets.QLineEdit(self.input_box)
        self.period_edit.setObjectName("period_edit")
        self.gridLayout_3.addWidget(self.period_edit, 3, 1, 1, 1)
        self.know_label = QtWidgets.QLabel(self.input_box)
        self.know_label.setObjectName("know_label")
        self.gridLayout_3.addWidget(self.know_label, 1, 0, 1, 1)
        self.interest_box = QtWidgets.QGroupBox(self.input_box)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.interest_box.sizePolicy().hasHeightForWidth())
        self.interest_box.setSizePolicy(sizePolicy)
        self.interest_box.setObjectName("interest_box")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.interest_box)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.eff_rate_box = QtWidgets.QGroupBox(self.interest_box)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.eff_rate_box.sizePolicy().hasHeightForWidth())
        self.eff_rate_box.setSizePolicy(sizePolicy)
        self.eff_rate_box.setObjectName("eff_rate_box")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.eff_rate_box)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.rate_label = QtWidgets.QLabel(self.eff_rate_box)
        self.rate_label.setObjectName("rate_label")
        self.gridLayout_6.addWidget(self.rate_label, 0, 0, 1, 1)
        self.rate_edit = QtWidgets.QLineEdit(self.eff_rate_box)
        self.rate_edit.setText("")
        self.rate_edit.setObjectName("rate_edit")
        self.gridLayout_6.addWidget(self.rate_edit, 0, 1, 1, 1)
        self.info_label = QtWidgets.QLabel(self.eff_rate_box)
        self.info_label.setObjectName("info_label")
        self.gridLayout_6.addWidget(self.info_label, 2, 0, 1, 1)
        self.gridLayout_4.addWidget(self.eff_rate_box, 0, 1, 1, 1)
        self.eff_calc_box = QtWidgets.QGroupBox(self.interest_box)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.eff_calc_box.sizePolicy().hasHeightForWidth())
        self.eff_calc_box.setSizePolicy(sizePolicy)
        self.eff_calc_box.setObjectName("eff_calc_box")
        self.formLayout_2 = QtWidgets.QFormLayout(self.eff_calc_box)
        self.formLayout_2.setObjectName("formLayout_2")
        self.nominal_rate_edit = QtWidgets.QLineEdit(self.eff_calc_box)
        self.nominal_rate_edit.setObjectName("nominal_rate_edit")
        self.formLayout_2.setWidget(
            0, QtWidgets.QFormLayout.FieldRole, self.nominal_rate_edit)
        self.nominal_rate_label = QtWidgets.QLabel(self.eff_calc_box)
        self.nominal_rate_label.setObjectName("nominal_rate_label")
        self.formLayout_2.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.nominal_rate_label)
        self.eff_rate_label = QtWidgets.QLabel(self.eff_calc_box)
        self.eff_rate_label.setObjectName("eff_rate_label")
        self.formLayout_2.setWidget(
            2, QtWidgets.QFormLayout.LabelRole, self.eff_rate_label)
        self.eff_period_edit = QtWidgets.QLineEdit(self.eff_calc_box)
        self.eff_period_edit.setObjectName("eff_period_edit")
        self.formLayout_2.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.eff_period_edit)
        self.eff_rate_edit = QtWidgets.QLineEdit(self.eff_calc_box)
        self.eff_rate_edit.setEnabled(True)
        self.eff_rate_edit.setReadOnly(True)
        self.eff_rate_edit.setObjectName("eff_rate_edit")
        self.formLayout_2.setWidget(
            2, QtWidgets.QFormLayout.FieldRole, self.eff_rate_edit)
        self.eff_period_label = QtWidgets.QLabel(self.eff_calc_box)
        self.eff_period_label.setObjectName("eff_period_label")
        self.formLayout_2.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.eff_period_label)
        self.gridLayout_4.addWidget(self.eff_calc_box, 1, 0, 1, 2)
        self.itype_box = QtWidgets.QGroupBox(self.interest_box)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.itype_box.sizePolicy().hasHeightForWidth())
        self.itype_box.setSizePolicy(sizePolicy)
        self.itype_box.setObjectName("itype_box")
        self.formLayout = QtWidgets.QFormLayout(self.itype_box)
        self.formLayout.setObjectName("formLayout")
        self.effective_radio = QtWidgets.QRadioButton(self.itype_box)
        self.effective_radio.setObjectName("effective_radio")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.LabelRole, self.effective_radio)
        self.nominal_radio = QtWidgets.QRadioButton(self.itype_box)
        self.nominal_radio.setObjectName("nominal_radio")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.LabelRole, self.nominal_radio)
        self.gridLayout_4.addWidget(self.itype_box, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.interest_box, 4, 0, 1, 3)
        self.amount_edit = QtWidgets.QLineEdit(self.input_box)
        self.amount_edit.setObjectName("amount_edit")
        self.gridLayout_3.addWidget(self.amount_edit, 2, 1, 1, 1)
        self.amount_label = QtWidgets.QLabel(self.input_box)
        self.amount_label.setObjectName("amount_label")
        self.gridLayout_3.addWidget(self.amount_label, 2, 0, 1, 1)
        self.amount_unit = QtWidgets.QLabel(self.input_box)
        self.amount_unit.setObjectName("amount_unit")
        self.gridLayout_3.addWidget(self.amount_unit, 2, 2, 1, 1)
        self.gridLayout_2.addWidget(self.input_box, 0, 0, 1, 1)
        self.output_box = QtWidgets.QGroupBox(self.frame)
        self.output_box.setObjectName("output_box")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.output_box)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.answer_label = QtWidgets.QLabel(self.output_box)
        self.answer_label.setObjectName("answer_label")
        self.gridLayout_5.addWidget(self.answer_label, 0, 0, 1, 1)
        self.answer_edit = QtWidgets.QLineEdit(self.output_box)
        self.answer_edit.setEnabled(True)
        self.answer_edit.setReadOnly(True)
        self.answer_edit.setObjectName("answer_edit")
        self.gridLayout_5.addWidget(self.answer_edit, 0, 1, 1, 1)
        self.output_info_box = QtWidgets.QTextEdit(self.output_box)
        self.output_info_box.setEnabled(True)
        self.output_info_box.setReadOnly(True)
        self.output_info_box.setObjectName("output_info_box")
        self.gridLayout_5.addWidget(self.output_info_box, 1, 0, 1, 2)
        self.gridLayout_2.addWidget(self.output_box, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(econ_ui)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        self.find_label.setBuddy(self.find_combo)
        self.period_label.setBuddy(self.period_edit)
        self.know_label.setBuddy(self.know_combo)
        self.rate_label.setBuddy(self.rate_edit)
        self.nominal_rate_label.setBuddy(self.nominal_rate_edit)
        self.eff_rate_label.setBuddy(self.eff_rate_edit)
        self.eff_period_label.setBuddy(self.eff_period_edit)
        self.amount_label.setBuddy(self.amount_edit)
        self.answer_label.setBuddy(self.answer_edit)

        self.retranslateUi(econ_ui)
        # self.buttonBox.accepted.connect(econ_ui.accept)
        self.buttonBox.rejected.connect(econ_ui.reject)
        QtCore.QMetaObject.connectSlotsByName(econ_ui)
        econ_ui.setTabOrder(self.find_combo, self.know_combo)
        econ_ui.setTabOrder(self.know_combo, self.amount_edit)
        econ_ui.setTabOrder(self.amount_edit, self.period_edit)
        econ_ui.setTabOrder(self.period_edit, self.effective_radio)
        econ_ui.setTabOrder(self.effective_radio, self.nominal_radio)
        econ_ui.setTabOrder(self.nominal_radio, self.rate_edit)
        econ_ui.setTabOrder(self.rate_edit, self.nominal_rate_edit)
        econ_ui.setTabOrder(self.nominal_rate_edit, self.eff_period_edit)
        econ_ui.setTabOrder(self.eff_period_edit, self.eff_rate_edit)
        econ_ui.setTabOrder(self.eff_rate_edit, self.answer_edit)
        econ_ui.setTabOrder(self.answer_edit, self.output_info_box)

    def retranslateUi(self, econ_ui):
        _translate = QtCore.QCoreApplication.translate
        econ_ui.setWindowTitle(_translate("econ_ui", "Engineering Economics"))
        self.input_box.setTitle(_translate("econ_ui", "Input"))
        self.find_combo.setItemText(0, _translate("econ_ui", "Present Worth"))
        self.find_combo.setItemText(1, _translate("econ_ui", "Future Worth"))
        self.find_combo.setItemText(2, _translate("econ_ui", "Annual Worth"))
        self.find_combo.setItemText(3, _translate("econ_ui", "Gradient"))
        self.find_combo.setItemText(4, _translate("econ_ui", "Capital Cost"))
        self.find_label.setText(_translate(
            "econ_ui", "What do you want to find?"))
        self.period_label.setText(_translate(
            "econ_ui", "Compounding periods:"))
        self.know_combo.setItemText(0, _translate("econ_ui", "Present Worth"))
        self.know_combo.setItemText(1, _translate("econ_ui", "Future Worth"))
        self.know_combo.setItemText(2, _translate("econ_ui", "Annual Worth"))
        self.know_combo.setItemText(3, _translate("econ_ui", "Gradient"))
        self.period_info.setText(_translate("econ_ui", "e.g. 6, 10"))
        self.period_edit.setText(_translate("econ_ui", "Enter a number"))
        self.know_label.setText(_translate("econ_ui", "What do you know?"))
        self.interest_box.setTitle(_translate("econ_ui", "Interest Rate"))
        self.eff_rate_box.setTitle(_translate(
            "econ_ui", "Enter effective rate:"))
        self.rate_label.setText(_translate(
            "econ_ui", "Effective Interest Rate:"))
        self.info_label.setText(_translate(
            "econ_ui", "<html><head/><body><p><span style=\" font-style:italic;\">Enter as a decimal (e.g. 0.04)</span></p></body></html>"))
        self.eff_calc_box.setTitle(_translate(
            "econ_ui", "Effective Interest Rate Calculation"))
        self.nominal_rate_label.setText(_translate(
            "econ_ui", "<html><head/><body><p>Nominal Rate <span style=\" font-style:italic;\">(as a decimal e.g. 0.04)</span></p></body></html>"))
        self.eff_rate_label.setText(_translate(
            "econ_ui", "Effective Interest Rate: "))
        self.eff_period_label.setText(_translate(
            "econ_ui", "Compounding periods within the nominal rate:"))
        self.itype_box.setTitle(_translate(
            "econ_ui", "What type do you have?"))
        self.effective_radio.setText(_translate("econ_ui", "Effective"))
        self.nominal_radio.setText(_translate("econ_ui", "Nominal"))
        self.amount_edit.setText(_translate("econ_ui", "Enter a number"))
        self.amount_label.setText(_translate(
            "econ_ui", "Enter the present worth:"))
        self.amount_unit.setText(_translate("econ_ui", "($)"))
        self.output_box.setTitle(_translate("econ_ui", "Output"))
        self.answer_label.setText(_translate("econ_ui", "Answer equals:"))
